Update i3 to 4.16.1
QubesOS/qubes-desktop-linux-i3 pull request #29
Opened 2019-07-23 03:22 UTC by dmoerner

Update i3 to upstream 4.16.1. Upstream changed the way they handle setting the titles of i3-generated containers for trees; adjusted the location of the Qubes-specific code to accommodate this.

Fixes https://github.com/QubesOS/qubes-issues/issues/5168.

2019-08-02 18:28 UTC, marmarek requested changes

2019-08-02 18:28 UTC, marmarek commented on i3.spec
> +- Update to upstream 4.16.1 and refresh Qubes patches.
Please add new changelog entry at the top, not replace it.

2019-08-03 00:35 UTC, marmarek approved these changes

2019-08-05 00:13 UTC, anadahz commented
@dmoerner Please note that i3 `v4.17` has been released (see: https://github.com/QubesOS/qubes-issues/issues/5168#issuecomment-518047908).

2019-09-17 23:33 UTC, anadahz commented
Thanks for working on this @dmoerner .
I pushed a new pull request for i3 v4.17.1 here: https://github.com/QubesOS/qubes-desktop-linux-i3/pull/30

2019-09-18 01:28 UTC, merged